### ISSUE TITLE
R_DSI_map.pdf downloads automatically when visiting the site

### ISSUE THREAD

**Issue by mikoontz** [d-rug/d-rug.github.io#20]
It seems that the default behavior for Chrome 59.0.3071.115 (Official Build) (64-bit) on MacOS Sierra Version 10.12.5 (16F73) is to download the .pdf file that is maybe just supposed to render as an image?

I see that file in the images/ directory, and only referenced in the html here: https://github.com/d-rug/d-rug.github.io/search?utf8=%E2%9C%93&q=R_DSI_map.pdf&type=

Maybe just because it's a .pdf?

**Comment by mikoontz** [comment]
Note that it is a pretty map, and I don't mind having a copy on my machine.

**Comment by ryanpeek** [comment]
I played with few diff options to get it to embed...ultimately I just need to convert the pdf to a png as it will play better with all browsers. Thanks for the heads up. All fixed now (I hope). Let me know if you have further problems.
