### ISSUE TITLE
add fall 2019 presentation/schedule to calendar

### ISSUE THREAD

**Issue by taylorreiter** [d-rug/d-rug.github.io#23]
@mcmaurer here is the schedule for Fall 2019! Would you be willing to add it to the google calendar?

26-Sep | Update Fest: Installing R, Rstudio, and updating packages
3-Oct | Intro to R: Vectors & Data Types
10-Oct | Intro to R: Subsetting Vectors
17-Oct | Evan Batzer on linear models in R
24-Oct | No presentation
31-Oct | Data Frames and Subsetting
7-Nov | Amy Collins on Google Earth Engine and other things
14-Nov | Factors
21-Nov | Dplyr: Select, Filter, Mutate
27-Nov | Thanksgiving; No working group
5-Dec | Dplyr: group_by, summarize, arrange, count
12-Dec | Intro to ggplot2

**Comment by MCMaurer** [comment]
Hey @taylorreiter sure thing, just not sure I have permissions for that- could you give me admin permission for the google group and see if that gives me access to the calendar too? Thanks!

**Comment by taylorreiter** [comment]
Hmm I don't think I have permission to give you admin permission...@MarthaWohlfeil or @ryanpeek can @MCMaurer be added so he can keep tabs on the website calendar?

**Comment by ryanpeek** [comment]
Hey folks, The calendar is actually built on a separate d-rug gmail account that was set up when D-RUG first began. I'll forward login info via email. It's rarely checked and was basically only used for the calendar and to set up an account to order stickers from. If we have other ideas for setting up a calendar in a different way, I'm open!
